### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by dritter**

### CODE REVIEW

**Comment by zakariaGatter** [comment]
Fix typo

**Comment by zakariaGatter** [comment]
Like what?!

**Comment by dritter** [comment]
Sorry for providing no text. Like [this](https://github.com/zakariaGatter/zshing/pull/1/files) 😛 

Just kidding. Stumbled upon a small typo in the update command:
```diff
-        zshing_update   [Update exist Plugins in youe system]
+        zshing_update   [Update existing Plugins in your system]
```

**Comment by zakariaGatter** [comment]
please can u use the plugins and tell me if u have any issues

**Pull request merged**
